version: "3.8"

services:
  rabbit:
    hostname: "rabbit"
    image: rabbitmq:3.8.4-management-alpine
    environment:
      RABBITMQ_DEFAULT_USER: "11111"
      RABBITMQ_DEFAULT_PASS: "11111"
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - "rabbitmq:/var/lib/rabbitmq"

volumes:
  rabbitmq:
    driver: local
